0:
  index: 0
  calibrated_center: 50
  calibrated_max: 71
  max_angle: 20
1:
  index: 1
  calibrated_center: 50
  calibrated_max: 71
  max_angle: 20
2:
  index: 2
  calibrated_center: 50
  calibrated_max: 71
  max_angle: 20
3:
  index: 3
  calibrated_center: 50
  calibrated_max: 71
  max_angle: 20
