fiducial_4x4:
  artag_squares:   4
  dict_num: 250
  log_translation_tag_from_world: [0.504537, 0.315765, 1.22443]
  log_rotation_tag_from_world: [-1.00638, 1.34476, 1.08971]
  artag_width_mm:  99.0 # measured by Matt  feb 10 2019
  artag_gap_mm:    50.0  # measured by Matt  feb 10 2019
fiducial_5x5:
  artag_squares:   5
  dict_num: 250
  log_translation_tag_from_world: [0.504537, 0.315765, 1.22443]
  log_rotation_tag_from_world: [-1.00638, 1.34476, 1.08971]

  artag_width_mm:  100.0 # measured by Matt  feb 10 2019
  artag_gap_mm:    50.0  # measured by Matt  feb 10 2019
