#!/bin/bash

function help () {
cat <<-END
Usage: jet COMMAND

Builds a new jet docker image for your host's architecture.

-h| --help           Show this message

commands:
build                Build the jet code
image                Build a new jet docker image
run                  Run an executable inside of a docker container
deploy               Run jet software on a vehicle or bench
broker               Configure the IPC Broker on this host
END
}

while [ -n "$1" ]; do
    case "$1" in
        -h | --help)
            help
            exit
            ;;
        *)
            break
            ;;
    esac
done

case "$1" in
"run")
    jet_run.sh "${@:2}"
    ;;
"build")
    jet_build.sh "${@:2}"
    ;;
"image")
	jet_image.sh "${@:2}"
	;;
"deploy")
	jet_deploy.sh "${@:2}"
	;;
"broker")
    jet_broker.sh "${@:2}"
    ;;
*)
    echo "Unknown option '$1': jet modes are [run|build|image|deploy|broker]"
    help
    ;;
esac
