width_pixels: 480
height_pixels: 270
# Bold, I know!
frames_per_second: 20
# Disable autofocus
auto_focus: 0
# Disables autoexposure...allegedly?
auto_exposure: 1
# Set a fixed exposure (The minimum)
exposure: 3

# Calling our shots: The camera we expect to be running
serial_number: 5CFD076E
