logged_channels:
  - camera_image_channel
  - fiducial_detection_channel
  - bq_state
  - force_sensor_output_channel
  - GoNoGo
  - GoNoGo_output
  - imu_1
  - imu_2
  - joystick_pitch
  - joystick_roll
  - joystick_yaw
  - pose
  - servo_command_channel
  - timesync_client
  - timesync_master
  - turbine_ignition
  - turbine_set_throttle
  - turbine_state

log_base_path: /logs/
